{"name": "Проверка ошибки при попытке авторизоваться под несуществующим пользователем (неверный login)", "status": "passed", "start": 1710083588564, "stop": 1710083588966, "uuid": "97080ee2-176c-4680-8f7d-6fd7c1bf035f", "historyId": "20e0a6da5ea1061b57ac8751d943f331", "testCaseId": "20e0a6da5ea1061b57ac8751d943f331", "fullName": "tests.test_login_courier.TestLoginCourier#test_login_courier_with_incorrect_login_not_found", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "CPR-2NBMZ33"}, {"name": "thread", "value": "22464-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}